# Generated by Django 5.2.4 on 2025-07-29 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_favorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
